seed: 12
monitor: pearson
metric_mode: max
early_stopping: True
patience: 1
min_delta: 0.0
save_top_k: 1
save_weights_only: True 
min_epochs: 1
max_epochs: 3
gradient_clip_val: 1.0
gpus: 1

batch_size: 4
accumulate_grad_batches: 8
loader_workers: 4

optimizer: Adam
learning_rate: 3.0e-05
encoder_learning_rate: 1.0e-05
layerwise_decay: 0.95
nr_frozen_epochs: 1
keep_embeddings_frozen: True
scheduler: constant

train_path: /mnt/data-zeus1/glushkovato/comet/wmt-metrics/scores-17-19.csv
val_path: /mnt/data-zeus1/glushkovato/comet/wmt-metrics/test19-scores.csv

model: VarianceEstimator
loss: custom
encoder_model: XLMR
pretrained_model: xlmr.large

layer: mix
scalar_mix_dropout: 0.1
pool: avg

dropout: 0.1
activations: Tanh
hidden_sizes: "1536,768"
final_activation: False
out_dim: 2

#val_check_interval: 0.01
